version: '3.1'
services:
  app:
    container_name: app
    image: 'kirill/domain'
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test